#ARRUS-202, ARRUS-203: fix issue with TGC in Matlab, enable the RF display.
us4useu/arrus pull request #285
Opened 2023-05-26 10:34 UTC by PiotrKarwat

ARRUS-202:
- TGC range is dependent on LNA and PGA values.
- TGC delay and sampling are verified and corrected.

ARRUS-203:
- RF display is now available in Matlab using plotRawRf or imageRawRf methods of the Us4R class. 
- The maximum amplitude of the undistorted* signal can be optionally marked.
* distortions due to the AFE input voltage exceeding the allowed range (nonlinear behaviour observed outside this range)

2023-06-15 08:27 UTC, pjarosik commented
@zkLog please revie

2023-06-16 13:59 UTC, zkLog requested changes
(for future versions):
1. Consider adding the label with information which lines are displayed.
2. Consider adding the option for plot orientation selection, to have possibility to plot line horizontally. 

For approving this version - correct the docstring in us4R_control_rawRfPwi.m script.

2023-06-16 13:59 UTC, zkLog commented on api/matlab/examples/Us4R_control_rawRfPwi.m
> +% Example script for b-mode imaging using plane waves and angular scanning
This is not script for b-mode imaging.

2023-06-19 11:39 UTC, PiotrKarwat commented on api/matlab/examples/Us4R_control_rawRfPwi.m
> +% Example script for b-mode imaging using plane waves and angular scanning
docstring corrected

2023-06-19 11:47 UTC, merged

2023-06-19 12:36 UTC, zkLog commented
Approved.